---
# tasks file for prometheus

- name: create configuration directory for user
  ansible.builtin.user:
    name: "{{ anible_user }}"
    state: present
  register: ansible_user_registered

- name: Define configuration directory
  ansible.builtin.set_fact:
    prometheus_config_dir: "{{ ansible_user_registered.home }}/prometheus"

- name: prometheus | create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/targets"

- name: prometheus | prometheus configuration file
  template:
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    src: etc-prometheus-prometheus-yml.j2
    mode: 0644
  register: prometheus_configuration

- name: prometheus | prometheus alert rules
  template:
    dest: "{{ prometheus_config_dir }}/rules/default-alert.rules.yml"
    force: true
    src: etc-prometheus-default-alert-rules-yml.j2
    mode: 0644
  register: prometheus_alert_rules

- name: prometheus | prometheus additional alert rules
  template:
    dest: "{{ prometheus_config_dir }}/rules/additional-alert.rules.yml"
    force: true
    src: "{{ prometheus_additional_rules_template }}"
    mode: 0644
  register: prometheus_alert_rules_additional

- name: prometheus | alertmanager configuration file
  template:
    dest: "{{ prometheus_config_dir }}/alertmanager.yml"
    force: true
    src: etc-prometheus-alertmanager-yml.j2
    mode: 0644
  register: prometheus_alertmanager_configuration

- name: prometheus | blackbox configuration file
  copy:
    dest: "{{ prometheus_config_dir }}/blackbox-exporter.yml"
    force: true
    src: etc-prometheus-blackbox-exporter.yml
    mode: 0644
  register: prometheus_blackboxexporter_configuration

- name: prometheus | file sd configs
  template:
    dest: "{{ prometheus_config_dir }}/targets/{{ item.groupname }}.yml"
    force: true
    src: file_sd_config-template-yml.j2
    mode: 0644
  with_items:
    - "{{ prometheus_sd_targets }}"
